---
abstract: 'Interface to Google Charts API'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >> (current maintainer)'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::MockObject: 0
  Test::More: 0.82
  Test::UseAllModules: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Google-Chart
no_index:
  directory:
    - docs
    - inc
    - t
requires:
  Encode: 0
  LWP::UserAgent: 0
  Moose: 0.92
  Scalar::Util: 0
  Sub::Exporter: 0
  URI: 0
  URI::Escape: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.09000_05
