---
abstract: 'Interface to Google Charts API'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >> (current maintainer)'
build_requires:
  Test::Compile: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Google-Chart
no_index:
  directory:
    - inc
    - t
requires:
  LWP::UserAgent: 0
  Moose: 0.54
  Scalar::Util: 0
  URI: 0
  URI::Escape: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05000
